### ISSUE TITLE
A lot of thanks for great tool

### ISSUE THREAD

**Issue by Avena83** [Tomtomgo/phearjs#10]
One first... I want to say for users who want parsing web sites " Use  https://github.com/Tomtomgo/phearjs ". It's really great when any wget, xidel and also...phantomjs.
Of course phearjs ussing phantomjs, like phantomjs ussing core linux )
But in a production when you need get information from more 1M web information - phearjs is best.
Thanks for autor.

---

Now, last question "how turn off download images like in  phantomjs?"
(phantomjs --load-images=false )

**Comment by ITsvetkoFF** [comment]
### Easy way

add `--load-images=false`  [here](https://github.com/Tomtomgo/phearjs/blob/master/phear.js#L16)

### Long way

It seems (have not tested) that in your `./config/config.json` you can add for the needed worker(s)

``` js
{
'autoLoadImages': false 
}
```

Note from [here](http://phantomjs.org/api/command-line.html) that your option looks not the same in config json.

---

actually this line  

``` js
workers[i].process = respawn(
["phantomjs", "--disk-cache=no", "--ignore-ssl-errors=yes", "--ssl-protocol=any", "lib/worker.js", "--config=" + worker_config]
)
```

may send to many settings to phantom. Can you please explore what is in `worker_config` variable? (Have no PhearJS iinstance near now)

**Comment by Avena83** [comment]
@ITsvetkoFF Thanks, but Easy way is working. But I am not sure about Long way...
