### ISSUE TITLE
Clarification: handling 404s and 301s

### ISSUE THREAD

**Issue by 34r7h** [Tomtomgo/phearjs#12]
Hi, amazing tool you've created! 

Prerender.io uses meta tags to help navigate crawlers for 404s and 301s. https://prerender.io/documentation/best-practices

Does phear have similar functionality or do you advise letting the server handle this directly?

**Comment by Tomtomgo** [comment]
Hi @irthos, there's no such thing. Is this something you consider important?

**Comment by 34r7h** [comment]
Hi @Tomtomgo we just launched our phear prerender environment today. We'll monitor and see how dead pages are handled by the crawlers. If anything weird happens, will let you know it's an important feature. Thanks!

**Comment by Tomtomgo** [comment]
Hi @irthos, is this issue still relevant?
