### ISSUE TITLE
SERVICE UNAVAILABLE

### ISSUE THREAD

**Issue by akloster** [Tomtomgo/phearjs#19]
I installed phearjs two ways, both with the current master revision: First try was system-wide under ubuntu, secondly via a nodejs docker container (+memcached).

Both fail when I try to request a web page:

"Ended process with status SERVICE UNAVAILABLE, MAXIMUM NUMBER OF ALLOWED CONNECTIONS REACHED.."

I increased the connections in the config.json file to 100 for both development and production. The status page works, and mentions the connection tries as "refused" and not as failed.

Any ideas what is going wrong here?

**Comment by alexpsi** [comment]
Same here. Solved it with npm install -g phantomjs

**Comment by Tomtomgo** [comment]
@akloster did @alexpsi's suggestion work for you?

Otherwise, did you install PhantomJS via [their downloads](http://phantomjs.org/download.html)?

**Comment by akloster** [comment]
I'm sorry for replying so late. I solved it by installing phantomjs. It should have occurred to me earlier!

**Comment by Tomtomgo** [comment]
Perfect!
