### ISSUE TITLE
Monitor individual worker capacity

### ISSUE THREAD

**Issue by falhashimi** [Tomtomgo/phearjs#3]
Hi Tom,

Each worker can handle a pool of requests, however there is currently no option or mechanism to monitor the number of queries each worker is handling, having this sort of information is useful for the following reasons:

1) It will help determine how efficient the Phear system against a certain set of concurrent continues request streams.
2)  It will provide a more granular set of information.
3) The information ca be used by an external program to moderate the traffic going to Phear, such as a load balancer.
4) It could help determine if there are any idle or zombie requests that are stuck in the pool.

Perhaps a good addition to the current API can be http://127.0.0.1:8100/?get_stats=workers 

The output should contain:

1) Worker information [name, port, current capacity]
2) Current url's being processed per worker.
3) Time each url has been in the pool.
4) All the above can be placed in JSON format, as an example:

``` json
{
    "workers": {
        "worker_a": {
            "port": "8031",
            "PID": "12512",
            "processing": "2",
            "status": "?",
            "currently_processing": {
                "request_1": {
                    "url": "http://www.google.com",
                    "time_in_pool": "20s",
                    "status": "processing",
                    "CPU": "cpu usage as a percentage",
                    "MEM": "Ram usage as a percentage"
                }
                "request_2": {
                    "url": "http://www.yahoo.com",
                    "time_in_pool": "10s",
                    "status": "idle",
                    "CPU": "cpu usage as a percentage",
                    "MEM": "Ram usage as a percentage"
                }
            }
        }
        "worker_b": {
            "port": "8032",
            "PID": "14512",
            "processing": "2",
            "status": "?",
            "currently_processing": {
                "request_1": {
                    "url": "http://www.jira.com",
                    "time_in_pool": "5s",
                    "status": "processing",
                    "CPU": "cpu usage as a percentage",
                    "MEM": "Ram usage as a percentage"
                }
                "request_2": {
                    "url": "http://www.happy.com",
                    "time_in_pool": "15s",
                    "status": "processing",
                    "CPU": "cpu usage as a percentage",
                    "MEM": "Ram usage as a percentage"
                }
            }
        }
    }
}
```

Thanks,
Fouad

**Comment by Tomtomgo** [comment]
Thanks Fouad, I think having a status page in general would be a good idea. Both as a HTML page that can be viewed in a browser, as well as some JSON version for automated processing.

I will definitely try to implement this soon.

**Comment by Tomtomgo** [comment]
A status page has been added. Check out the new version and take a look at http://localhost:8100/status! Would a JSON version still be necessary?

**Comment by falhashimi** [comment]
Thank you Tom! the page has very helpful information.

Regards,
Fouad

**Comment by Tomtomgo** [comment]
Cheers @falhashimi, I'll close this for now and maybe implement additional info later.
