### ISSUE TITLE
Add render page feature

### ISSUE THREAD

**Issue by ITsvetkoFF** [Tomtomgo/phearjs#6]
As follows:

request should be `http://localhost:8100?fetch_url=domain.com&render=jpg`

response:

``` javascript
{
  "success": true,
  "input_url": "http://such-website.com",
  "final_url": "http://www.such-website.com/",
  "request_headers": {},
  "response_headers": {
    "date": "Sun, 08 Feb 2015 15:11:22 GMT",
    "content-encoding": "gzip",
    "expires": "Sun, 08 Feb 2015 15:12:33 GMT",
    "vary": "Accept-Encoding",
    "cache-control": "max-age=60",
    "last-modified": "Sun, 08 Feb 2015 15:11:33 GMT",
    "content-type": "text/html; charset=utf-8"
  },
  "had_js_errors": false,
  "content": "<rendered HTML>",
  "rendered": "path/to/img.jpg"
}
```

And also there should be some config file to store images path.

**Comment by ITsvetkoFF** [comment]
This feature should fit perfectly to phearjs! And I am wondering why it is not implemented yet. It looks rather trivial and I think that users implement it by themselves. Am I right? :)

**Comment by Tomtomgo** [comment]
Thanks for the input @ITsvetkoFF, seems like a nice idea. You're right that other did this by themselves before.

But, we should think about how this can work. Currently Phear can return the raw HTML, or a JSON with the HTML inside. We could extend the behaviour by allowing it to return an image instead of JSON, or to give a URL to download the image inside the JSON. Also, when images are saved on disk, they should also be deleted some time.

What do you think?

**Comment by ITsvetkoFF** [comment]
@Tomtomgo clever thoughts.

I've suggested to add 

``` javascript
  "rendered": "path/to/img.jpg"
```

to the response.

As for deleting, one can implement some `node-schedule` script to clear old folders. By default I'd create new folder every day.

I think that it is reasonable to add _**render image**_ feature to Phear just because that's the only possible place where image can be rendered, and there is a number of purposes when you may need such a screenshot.

**Comment by Tomtomgo** [comment]
Yes, looks good. If you get the time to add it, I'd be happy to merge in a pull request! Otherwise, this is definitely something I'd like to add in the future.

**Comment by Tomtomgo** [comment]
Merged, finally! Thanks @ITsvetkoFF :+1:
