### ISSUE TITLE
Rubygem created

### ISSUE THREAD

**Issue by joaquinmoreira** [Tomtomgo/phearjs#7]
I created [**phearb**](https://github.com/joaquinrulin/phearb), a ruby gem for connecting to a phearb server very easily!

Just think you need to know this in case you want to refer it on the README or just check it out!

Is in an early stage yet usable. As i need more features in my app i'm gonna be adding it to the gem.

Thanks

**Comment by Tomtomgo** [comment]
Very cool @joaquinrulin :100::tophat:! I added this to the [README](https://github.com/Tomtomgo/phearjs/blob/master/README.md).
