### ISSUE TITLE
It's working perfect, but short time

### ISSUE THREAD

**Issue by Avena83** [Tomtomgo/phearjs#9]
It's working perfect, but short time. After few hours it's stoping to hear on 8100 port. Say me please how can I fix in config file? I need service that working without stoping. Thanks a lot for autor.

**Comment by Tomtomgo** [comment]
That could potentially be a hard problem to fix, as there can be many causes for it. However, first thing I would check is the version of PhantomJS you're using. It should be 2+.

From the command line:

``` shell
phantomjs -v
```

If that's less than 2.1, try [installing the latest version](http://phantomjs.org/download.html).

**Comment by Avena83** [comment]
root@sv2:~# phantomjs -v
2.1.1

**Comment by Avena83** [comment]
root@sv2:~/phearjs# cat /etc/issue
Debian GNU/Linux 8 \n \l
root@sv2:~/phearjs# cat /etc/debian_version
8.4
root@sv2:~/phearjs# uname -m
x86_64
root@sv2:~/phearjs# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:        8.4
Codename:       jessie
root@sv2:~# phantomjs -v
2.1.1
root@sv2:~# nodejs -v
v6.2.2
root@sv2:~# npm -v
3.9.5
root@sv2:~# memcached -help | grep memcached
memcached 1.4.21

**Comment by Tomtomgo** [comment]
Hmm. So in that case you could try to use Ubuntu or try to find out the cause of the issue yourself.

**Comment by Avena83** [comment]
3 minutes ago only finished check...all things working well. Thanks @Tomtomgo 

To solve troubles used https://github.com/foreverjs/forever
